### ISSUE TITLE
Bug when version checking DIsplay Link Manager & Ignoring DEPNotify

### ISSUE THREAD

**Issue by Uggbert** [robjschroeder/App-Auto-Patch#55]
From the logs:

App Auto-Patch: 2024-02-05 22:11:38 - [INFO] Found DisplayLink Manager.app version 1.10.0
App Auto-Patch: 2024-02-05 22:11:54 - [NOTICE] --- New version: 1.9
App Auto-Patch: 2024-02-05 22:11:54 - [NOTICE] Queueing displaylinkmanager

I think its maybe interpreting 1.10 as 1.0 ?

**Comment by robjschroeder** [comment]
Hey @Uggbert, it's not necessarily interpreting `1.10` as `1.0`. It's looking to see if `"$previousVersion" == "$appNewVersion"`. And we couldn't use a greater-than type of operator because how there are so many vendors out there that include letters or other types of things in their versioning strings. Weird though that the new version is `1.9` and you seem to have `1.10` installed, this looks like a problem with the Installomator label for `displaylinkmanager`

**Comment by Uggbert** [comment]
Ah ok I see, I can log an issue over at installomator or check the issues
list there to see if it's a known issue, for now I will exclude it from the
app auto patcher checks.

Thanks again, very slick implementation with minimal setup for me! Always a
bonus, i'll be using this in production for sure once I do a bit more
testing.

**Comment by Uggbert** [comment]
Update, its a known issue over at installomator: https://github.com/Installomator/Installomator/issues/1427

This can be closed.
